version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - './config.toml:/app/config.toml'
    ports:
      - "8088:8088"
  simple-curl:
    build:
      context: .
      dockerfile: Dockerfile